@startuml

"Usuario" as user
"Administrador" as adm

"Autenticar" as (auth)
"Gerenciar Questões" as (g_quest)
"Gerenciar Administradores" as (g_adm)
"Sair da conta" as (exit_user)
"Gerenciar perfil" as (g_user)
"Fazer questão" as (m_quest)
"Criar conta" as (create_user)

user --> (auth)
user --> (exit_user)
user --> (g_user)
user --> (m_quest)
user --> (create_user)
adm --> (auth)
adm --> (exit_user)
adm --> (g_quest)
adm --> (g_adm)

@enduml